version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx-blog
    ports:
      - "8100:8100"
    volumes:
      - "~/project/my-blog:/etc/nginx/www/my-blog"
      - "~/nginx/nginx.conf:/etc/nginx/nginx.conf"
      - "~/nginx/conf.d:/etc/nginx/conf.d"
      - "~/nginx/log:/var/log/nginx"